using System;
using System.Collections.Generic;
using System.Text;
using Eko95.Models;
namespace Eko95.Services
{
    //PuklaGumaSifra
    public class MockDataStreets
    {
        public static List<StreetModel> StreetsOfNS = new List<StreetModel>()
            {
                #region uliceNS
               new StreetModel {  Name="Bulevar oslobođenja",PossibleBuildingsNumbers=new List<string>{"0","2","4","4a","4b","6","8","10","12","14","16","18","20","22","24","26","28","30","30a","30b","32","34","36","38" } },
               new StreetModel {  Name= "Bulevar Jaše Tomića" },
               new StreetModel {  Name= "Bulevar kralja Petra I" },
               new StreetModel {  Name= "Bulevar cara Lazara" },
               new StreetModel {  Name= "Bulevar despota Stefana" },
               new StreetModel {  Name= "Bulevar Mihajla Pupina"},
               new StreetModel {  Name= "Bulevar Evrope"},
               new StreetModel {  Name= "Subotički bulevar"},
               new StreetModel {  Name= "Bulevar patrijarha Pavla (Somborski bulevar)"},
               new StreetModel {  Name= "Bulevar vojvode Stepe" },
               new StreetModel {  Name= "Bulevar kneza Miloša" },
               new StreetModel {  Name= "Bulevar Jovana Dučića" },
               new StreetModel {  Name= "Bulevar Slobodana Jovanović" },
               new StreetModel {  Name= "Pozorišni trg" },
               new StreetModel {  Name= "Trg 1. maja" },
               new StreetModel {  Name= "Trg 23. oktobra" },
               new StreetModel {  Name="Trg 27. marta" },
               new StreetModel {  Name="Trg carice Milice" },
               new StreetModel {  Name="Trg Dositeja Obradovića"},
               new StreetModel {  Name="Trg Feher Ferenca" },
               new StreetModel {  Name="Trg galerija" },
               new StreetModel {  Name="Trg Komenskog" },
               new StreetModel {  Name="Trg majke Jevrosime" },
               new StreetModel {  Name="Trg Marije Trandafil" },
               new StreetModel {  Name="Trg mira" },
               new StreetModel {  Name="Trg mladenaca" },
               new StreetModel {  Name="Trg neznanog junaka" },
               new StreetModel {  Name="Trg republike" },
               new StreetModel {  Name="Trg slobode" },
               new StreetModel {  Name="Trifkovićev trg" },
               new StreetModel {  Name="Žitni trg" },
               new StreetModel {  Name="Zmaj Jovina" },
               new StreetModel {  Name="Dunavska" },
               new StreetModel {  Name="Ilije Ognjanovića" },
               new StreetModel {  Name="Laze Telečkog" },
               new StreetModel {  Name="Miletićeva" },
               new StreetModel {  Name="Pašićeva" } ,
               new StreetModel {  Name="Zlatne grede" },
               new StreetModel {  Name="Njegoševa" },
               new StreetModel {  Name="Futoška" },
               new StreetModel {  Name="Jevrejska" },
               new StreetModel {  Name="Šafarikova" },
               new StreetModel {  Name="Masarikova" },
               new StreetModel {  Name="Jovana Subotića" },
               new StreetModel {  Name="Vojvode Bojovića" },
               new StreetModel {  Name="Lukijana Mušickog" },
               new StreetModel {  Name="Vojvode Šupljikca" },
               new StreetModel {  Name="Vuka Karadžića" },
               new StreetModel {  Name="Pap Pavla" },
               new StreetModel {  Name="Narodnih heroja" },
                new StreetModel {  Name="Železnička" },
               new StreetModel {  Name="Vase Stajića" },
                new StreetModel {  Name="Maksima Gorkog" },
               new StreetModel {  Name="Radnička" },
                new StreetModel {  Name="Stražilovska" },
                new StreetModel {  Name="Stevana Musića" },
                new StreetModel {  Name="Vojvode Mišića" },
                new StreetModel {  Name="Jovana Đorđevića" },
                new StreetModel {  Name="Vladike Platona" },
                new StreetModel {  Name="Sutjeska" },
                 new StreetModel {  Name="Zarka Zrenjanina" },
                 new StreetModel {  Name="Kej žrtava racije" },
                new StreetModel {  Name="Beogradski kej" },
                 new StreetModel {  Name="Sunčani kej" },
                 new StreetModel {  Name="Temerinska" },
                 new StreetModel {  Name="Gundulićeva" },
                 new StreetModel {  Name="Almaška" },
                 new StreetModel {  Name="Kosovska" },
                 new StreetModel {  Name="Tekelijina" },
                 new StreetModel {  Name="Marka Miljanova" },
                 new StreetModel {  Name="Save Vukovica" },
                 new StreetModel {  Name="Bele Njive" },
                 new StreetModel {  Name="Djordja Rajkovica" },
                 new StreetModel {  Name="Filipa Visnjica" },
                 new StreetModel {  Name="Svetosavska" },
                  new StreetModel {  Name="Matice Srpske" },
                  new StreetModel {  Name="Sterijina" },
                  new StreetModel {  Name="Baranjska" },
                  new StreetModel {  Name="Pecka" },
                  new StreetModel {  Name=  "Petra Kocica" },
                  new StreetModel {  Name=  "Milosa Obilica" },
                  new StreetModel {  Name=  "Pavla Stamatovica" },
                  new StreetModel {  Name=  "Koce Kolarova" },
                  new StreetModel {  Name=  "Jase Ignjatovica" },
                  new StreetModel {  Name=  "Patrijarha Carnojevica" },
                  new StreetModel {  Name=  "Hadzi Cvetica" },
                  new StreetModel {  Name=  "Jug Bogdana" },
                  new StreetModel {  Name=  "Skerliceva" },
                  new StreetModel {  Name=  "Daniciceva" },
                  new StreetModel {  Name=  "Sumadijska" },
                  new StreetModel {  Name=  "Episkopa Visariona" },
                  new StreetModel {  Name=  "Zarka Vasiljevica" },
                  new StreetModel {  Name=  "Stevana Milovanova" },
                  new StreetModel {  Name=  "Milosa Bajica" },
                  new StreetModel {  Name=  "Dusana Vasiljeva" },
                  new StreetModel {  Name=  "Milana Rakica" },
                  new StreetModel {  Name=  "Venizelosova" },
                  new StreetModel {  Name=  "Koste Hadzi mladjeg" },
                  new StreetModel {  Name=  "Zemljane Cuprije" },
                  new StreetModel {  Name=  "Marka Nesica" },


                  new StreetModel {  Name=  "Kisačka" },
                  new StreetModel {  Name=  "Jovana Cvijića" },
                  new StreetModel {  Name=  "Dositejeva"},
                  new StreetModel {  Name=  "Karađorđeva" },
                  new StreetModel {  Name=  "Branka Radičevića" },
                  new StreetModel {  Name=  "Radoja Domanovića" },
                  new StreetModel {  Name=  "Partizanska" },
                    //Grbavica

                  new StreetModel {  Name=  "Braće Ribnikar" },
                   new StreetModel {  Name= "Miše Dimitrijevića" },
                   new StreetModel {  Name= "Danila Kiša" },
                   new StreetModel {  Name= "Vojvođanska" },
                   new StreetModel {  Name= "Lasla Gala" },
                   new StreetModel {  Name= "Puškinova" },
                   new StreetModel {  Name= "Gogoljeva" },
                   new StreetModel {  Name= "Tolstojeva" },
                   new StreetModel {  Name= "Vojvode Knićanina" },

                    //limani

                   new StreetModel {  Name= "Fruškogorska" },
                   new StreetModel {  Name= "Narodnog fronta" },
                    new StreetModel {  Name="Dr Sime Miloševića" },
                   new StreetModel {  Name= "Drage Spasić" },
                    new StreetModel {  Name="Dragiše Brašovana" },
                    new StreetModel {  Name="Dr Ivana Ribara" },
                    new StreetModel {  Name="Resavska" },
                    new StreetModel {  Name="Ravanička" },

                    new StreetModel {  Name="Balzakova" },
                    new StreetModel {  Name="Podgorička" },
                    new StreetModel {  Name="Šekspirova" },
                    new StreetModel {  Name="Iva Andrića" },
                    new StreetModel {  Name="1300 kaplara" },
                    new StreetModel {  Name="Banović Strahinje" },


                    new StreetModel {  Name="Cara Dušana" },
                    new StreetModel {  Name="Hajduk Veljkova" },
                    new StreetModel {  Name="Novosadskog sajma" },
                    new StreetModel {  Name="Rumenačka" },
                    new StreetModel {  Name="Braće Popović" },
                    new StreetModel {  Name="Hadži Ruvimova" },
                    new StreetModel {  Name="Stevana Mokranjca" },
                    //Telep

                    new StreetModel {  Name="Ilariona Ruvarca" },
                   new StreetModel {  Name="Heroja Pinkija" },
                    new StreetModel {  Name="Ćirila i Metodija" },
                    new StreetModel {  Name="Petefi Šandora" },
                    new StreetModel {  Name="Subotička" },
                   new StreetModel {  Name= "Vršačka" },
                    new StreetModel {  Name="Adi Endrea" },
                    new StreetModel {  Name="Bogdana Šuputa" },
                    new StreetModel {  Name="Feješ Klare" },
                    new StreetModel {  Name="Šarplaninska" },
                    //Detelinara

                    new StreetModel {  Name="Kornelija Stankovića" },
                   new StreetModel {  Name= "Milenka Grčića" },
                   new StreetModel {  Name= "Janka Veselinovića" },
                    new StreetModel {  Name="Janka Čmelika" },
                    new StreetModel {  Name="Dr Svetislava Kasapinovića" },
                    new StreetModel {  Name="Ilije Birčanina" },
                   // Bistrica (Novo Naselje)

                    new StreetModel {  Name="Radivoja Raše Radujkova" },
                    new StreetModel {  Name="Stojana Novakovića" },
                    new StreetModel {  Name="Đorđa Nikšića Johana" },
                    new StreetModel {  Name="Todora Jovanovića Toze" },
                   new StreetModel {  Name="Mileve Marić" },
                   new StreetModel {  Name= "Kaće Dejanović" },
                    new StreetModel {  Name="Seljačkih buna" },
                   new StreetModel {  Name= "Partizanskih baza" },
                    new StreetModel {  Name="Braće Dronjak" },
                    new StreetModel {  Name="Bate Brkića" },
                    new StreetModel {  Name="Dušana Danilovića" },
                    new StreetModel {  Name="Stevana Hladnog" },
                    new StreetModel {  Name="Antuna Urbana" },
                    //Adice

                    new StreetModel {  Name="Branka Ćopića" },
                    new StreetModel {  Name="Slavujeva" },
                    new StreetModel {  Name="Sime Šolaje" },
                    new StreetModel {  Name="Podunavska" },
                    //Klisa

                    new StreetModel {  Name="Temerinski put" },
                    new StreetModel {  Name="Sentandrejski put" },
                    new StreetModel {  Name="Primorska" },
                    new StreetModel {  Name="Otokara Keršovanija" },
                    new StreetModel {  Name="Čenejska" },
                    new StreetModel {  Name="Paje Radosavljevića" },
                    new StreetModel {  Name="Velebitska" },
                    new StreetModel {  Name= "Savska" }
                    #endregion
         };
    }
}
